# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('mac_addr', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_alias', models.CharField(default='', max_length=200)),
                ('ip_addr', models.CharField(max_length=15)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx', models.FloatField()),
                ('rx', models.FloatField()),
                ('rssi', models.CharField(max_length=15, verbose_name='signal strength')),
                ('connection_time', models.DateTimeField()),
                ('time_of_sample', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wifimanager.Client')),
            ],
        ),
    ]
